"""tables realationships v1

Revision ID: 7ef6e85e2563
Revises: f6ed1b930468
Create Date: 2022-11-15 00:30:38.090949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef6e85e2563'
down_revision = 'f6ed1b930468'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryproduct', sa.Column('inventory_date', sa.DateTime(), nullable=False, comment='Created at. Time when the record was created.'))
    op.add_column('product', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('subsidiary_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('inventory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'subsidiary', ['subsidiary_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'product', 'inventoryproduct', ['inventory_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'product', 'client', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product', schema='public', type_='foreignkey')
    op.drop_column('product', 'inventory_id')
    op.drop_column('product', 'subsidiary_id')
    op.drop_column('product', 'client_id')
    op.drop_column('inventoryproduct', 'inventory_date')
    # ### end Alembic commands ###
