"""empty message

Revision ID: f6ed1b930468
Revises: 
Create Date: 2022-11-14 07:55:14.168927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ed1b930468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created at. Time when the record was created.'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Updated at. Time when the record was updated.'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('adress', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('inventoryproduct',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created at. Time when the record was created.'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Updated at. Time when the record was updated.'),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created at. Time when the record was created.'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Updated at. Time when the record was updated.'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('subsidiary',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created at. Time when the record was created.'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Updated at. Time when the record was updated.'),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('adress', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subsidiary', schema='public')
    op.drop_table('product', schema='public')
    op.drop_table('inventoryproduct', schema='public')
    op.drop_table('client', schema='public')
    # ### end Alembic commands ###
